"""Ollama-backed bounded quality-review executor for multi-agent research."""

from __future__ import annotations

import json
import time
from collections.abc import Callable
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from app.research.research_quality_review_executor import (
    ResearchQualityDecision,
    ResearchQualityReview,
    ResearchQualityReviewExecutionResult,
    ResearchQualityReviewExecutor,
    ResearchQualityReviewExecutorError,
    ResearchQualityScores,
    ResearchRevisionRequest,
    ResearchRevisionSeverity,
)
from app.research.research_synthesis_executor import ResearchSynthesizedReport
from app.schemas.research_agent_assignment import ResearchAgentTaskAssignment
from app.services.ollama_client import OllamaClient, OllamaClientError

LOCAL_QUALITY_REVIEW_INSTRUCTIONS = """\
You are a bounded research-report quality reviewer.

Evaluate only the supplied report. Do not invent sources, citations, claims, or
facts that are not present in the report.

Score each dimension from 0.0 to 1.0:
- completeness
- evidence_coverage
- citation_quality
- source_quality
- logical_consistency
- clarity

Decision rules:
- approved: no required revision is needed for the report as presented.
- revision_required: the report is usable but one or more concrete revisions
  are required.
- rejected: the report is fundamentally unusable for the requested review.

This local reviewer is advisory, not an authoritative final factual verifier.
Use conservative scores when the report does not expose enough evidence,
citation, or source-quality information to justify a high score.

For revision_required, provide at least one required revision.
For approved, do not provide required revisions or a rejection_reason.
For rejected, provide a nonblank rejection_reason.

Return only the structured JSON result matching the supplied schema.
"""


class LocalQualityRevisionJudgment(BaseModel):
    """One revision request generated by the bounded local reviewer."""

    model_config = ConfigDict(extra="forbid")

    target_type: str
    target_id: str
    issue: str
    required_action: str
    severity: ResearchRevisionSeverity
    required: bool = True


class LocalResearchQualityJudgment(BaseModel):
    """Structured local judgment before production IDs are attached."""

    model_config = ConfigDict(extra="forbid")

    decision: ResearchQualityDecision
    completeness: float = Field(ge=0.0, le=1.0)
    evidence_coverage: float = Field(ge=0.0, le=1.0)
    citation_quality: float = Field(ge=0.0, le=1.0)
    source_quality: float = Field(ge=0.0, le=1.0)
    logical_consistency: float = Field(ge=0.0, le=1.0)
    clarity: float = Field(ge=0.0, le=1.0)
    summary: str
    strengths: list[str] = Field(default_factory=list)
    revision_requests: list[LocalQualityRevisionJudgment] = Field(
        default_factory=list
    )
    rejection_reason: str | None = None


class InMemoryResearchReportRegistry:
    """Resolve synthesized reports by agent output-reference ID."""

    def __init__(self) -> None:
        self._reports: dict[str, ResearchSynthesizedReport] = {}

    def register(
        self,
        *,
        reference_id: str,
        report: ResearchSynthesizedReport,
    ) -> None:
        """Register one report under a nonblank unique reference ID."""

        key = self._normalize(reference_id)
        if key in self._reports:
            raise ValueError(
                f"research report reference already registered: {reference_id}"
            )
        self._reports[key] = report

    def resolve(self, reference_id: str) -> ResearchSynthesizedReport:
        """Return one registered report or fail explicitly."""

        key = self._normalize(reference_id)
        try:
            return self._reports[key]
        except KeyError as exc:
            raise KeyError(
                f"research report reference not found: {reference_id}"
            ) from exc

    @staticmethod
    def _normalize(value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("reference_id must not be blank")
        return cleaned.casefold()


class LocalResearchQualityReviewExecutor(ResearchQualityReviewExecutor):
    """Review a registered synthesized report with Ollama structured output."""

    def __init__(
        self,
        *,
        client: OllamaClient,
        model: str,
        report_registry: InMemoryResearchReportRegistry,
        num_predict: int = 768,
        temperature: float = 0.0,
        seed: int = 42,
        review_id_factory: Callable[[], str] | None = None,
    ) -> None:
        if not model.strip():
            raise ValueError("model must not be blank")
        if num_predict < 1:
            raise ValueError("num_predict must be at least 1")
        if temperature < 0:
            raise ValueError("temperature must be nonnegative")

        self._client = client
        self._model = model.strip()
        self._report_registry = report_registry
        self._num_predict = num_predict
        self._temperature = temperature
        self._seed = seed
        self._review_id_factory = (
            review_id_factory
            or (lambda: f"local-quality-review-{uuid4()}")
        )

    @property
    def model(self) -> str:
        """Return configured local model."""

        return self._model

    def execute(
        self,
        assignment: ResearchAgentTaskAssignment,
    ) -> ResearchQualityReviewExecutionResult:
        """Resolve, review, and normalize one synthesized report."""

        report_reference_id = self._report_reference_id(assignment)
        try:
            report = self._report_registry.resolve(report_reference_id)
        except KeyError as exc:
            raise ResearchQualityReviewExecutorError(
                str(exc),
                code="RESEARCH_REPORT_NOT_FOUND",
                retryable=False,
                details={"reference_id": report_reference_id},
            ) from exc

        prompt = (
            f"{LOCAL_QUALITY_REVIEW_INSTRUCTIONS}\n\n"
            "Evaluate this report and return only the structured result.\n\n"
            + json.dumps(
                {
                    "report": report.model_dump(mode="json"),
                    "assignment": {
                        "objective": assignment.objective,
                        "instructions": list(assignment.instructions),
                        "acceptance_criteria": list(
                            assignment.acceptance_criteria
                        ),
                    },
                },
                ensure_ascii=False,
            )
        )

        started_at = time.perf_counter()
        try:
            generated = self._client.generate(
                model=self._model,
                prompt=prompt,
                think=False,
                stream=False,
                keep_alive="5m",
                num_predict=self._num_predict,
                temperature=self._temperature,
                seed=self._seed,
                response_format=(
                    LocalResearchQualityJudgment.model_json_schema()
                ),
            )
        except OllamaClientError as exc:
            raise ResearchQualityReviewExecutorError(
                str(exc),
                code="LOCAL_QUALITY_REVIEW_OLLAMA_ERROR",
                retryable=True,
                details={"model": self._model},
            ) from exc

        duration_ms = max(
            0,
            int((time.perf_counter() - started_at) * 1000),
        )

        if generated.done_reason == "length":
            raise ResearchQualityReviewExecutorError(
                "local quality review generation stopped by length",
                code="LOCAL_QUALITY_REVIEW_LENGTH_LIMIT",
                retryable=True,
                details={"model": self._model},
            )
        if not generated.response.strip():
            raise ResearchQualityReviewExecutorError(
                "local quality review generation returned empty response",
                code="LOCAL_QUALITY_REVIEW_EMPTY_RESPONSE",
                retryable=True,
                details={"model": self._model},
            )

        try:
            judgment = LocalResearchQualityJudgment.model_validate_json(
                generated.response
            )
        except ValidationError as exc:
            raise ResearchQualityReviewExecutorError(
                "local quality review returned invalid structured output",
                code="LOCAL_QUALITY_REVIEW_INVALID_RESPONSE",
                retryable=True,
                details={"model": self._model},
            ) from exc

        review_id = self._new_review_id()
        review = self._production_review(
            review_id=review_id,
            report=report,
            judgment=judgment,
        )

        return ResearchQualityReviewExecutionResult(
            review=review,
            tool_call_count=1,
            duration_ms=duration_ms,
            input_token_count=generated.prompt_eval_count,
            output_token_count=generated.eval_count,
            metadata={
                "provider": "ollama-local",
                "model": self._model,
                "authoritative": "false",
                "role": "bounded_quality_reviewer",
                "think": "false",
            },
        )

    @staticmethod
    def _report_reference_id(
        assignment: ResearchAgentTaskAssignment,
    ) -> str:
        report_inputs = [
            item
            for item in assignment.inputs
            if item.reference_type == "research_report"
        ]
        if len(report_inputs) != 1:
            raise ResearchQualityReviewExecutorError(
                "quality review assignment must contain exactly "
                "one research_report input",
                code="INVALID_QUALITY_REVIEW_INPUT",
                retryable=False,
            )
        return report_inputs[0].reference_id

    def _new_review_id(self) -> str:
        value = self._review_id_factory()
        if not value.strip():
            raise ResearchQualityReviewExecutorError(
                "review_id factory returned blank value",
                code="INVALID_QUALITY_REVIEW_ID",
                retryable=False,
            )
        return value.strip()

    @staticmethod
    def _production_review(
        *,
        review_id: str,
        report: ResearchSynthesizedReport,
        judgment: LocalResearchQualityJudgment,
    ) -> ResearchQualityReview:
        normalized = _normalize_quality_judgment(
            report=report,
            judgment=judgment,
        )
        revision_requests = [
            ResearchRevisionRequest(
                revision_id=f"{review_id}-revision-{index:03d}",
                target_type=item.target_type,
                target_id=item.target_id,
                issue=item.issue,
                required_action=item.required_action,
                severity=item.severity,
                required=item.required,
                metadata={
                    "provider": "ollama-local",
                    "authoritative": "false",
                    "semantic_repair": (
                        "true" if normalized.repaired else "false"
                    ),
                },
            )
            for index, item in enumerate(
                normalized.judgment.revision_requests,
                start=1,
            )
        ]

        return ResearchQualityReview(
            review_id=review_id,
            report_id=report.report_id,
            decision=normalized.judgment.decision,
            scores=ResearchQualityScores(
                completeness=normalized.judgment.completeness,
                evidence_coverage=normalized.judgment.evidence_coverage,
                citation_quality=normalized.judgment.citation_quality,
                source_quality=normalized.judgment.source_quality,
                logical_consistency=(
                    normalized.judgment.logical_consistency
                ),
                clarity=normalized.judgment.clarity,
            ),
            summary=normalized.judgment.summary,
            strengths=normalized.judgment.strengths,
            revision_requests=revision_requests,
            rejection_reason=normalized.judgment.rejection_reason,
            metadata={
                "provider": "ollama-local",
                "authoritative": "false",
                "role": "bounded_quality_reviewer",
                "semantic_repair": (
                    "true" if normalized.repaired else "false"
                ),
            },
        )


class _NormalizedQualityJudgment(BaseModel):
    """Deterministically repaired local quality judgment."""

    model_config = ConfigDict(extra="forbid")

    judgment: LocalResearchQualityJudgment
    repaired: bool


def _normalize_quality_judgment(
    *,
    report: ResearchSynthesizedReport,
    judgment: LocalResearchQualityJudgment,
) -> _NormalizedQualityJudgment:
    """Repair cross-field LLM inconsistencies conservatively."""

    repaired = False
    decision = judgment.decision
    revision_requests = list(judgment.revision_requests)
    rejection_reason = judgment.rejection_reason

    required_revisions = [
        item
        for item in revision_requests
        if item.required
    ]

    if decision is ResearchQualityDecision.APPROVED:
        if rejection_reason is not None:
            decision = ResearchQualityDecision.REJECTED
            revision_requests = []
            repaired = True
        elif required_revisions:
            decision = ResearchQualityDecision.REVISION_REQUIRED
            rejection_reason = None
            repaired = True

    if decision is ResearchQualityDecision.REVISION_REQUIRED:
        rejection_reason = None
        if not any(item.required for item in revision_requests):
            revision_requests.append(
                LocalQualityRevisionJudgment(
                    target_type="report",
                    target_id=report.report_id,
                    issue=(
                        "The local reviewer marked the report as "
                        "requiring revision without supplying a "
                        "concrete required revision."
                    ),
                    required_action=(
                        "Revise the report to address the quality "
                        "issues identified in the review summary."
                    ),
                    severity=ResearchRevisionSeverity.MAJOR,
                    required=True,
                )
            )
            repaired = True

    if decision is ResearchQualityDecision.REJECTED:
        revision_requests = []
        if rejection_reason is None or not rejection_reason.strip():
            rejection_reason = judgment.summary.strip()
            repaired = True

    normalized = judgment.model_copy(
        update={
            "decision": decision,
            "revision_requests": revision_requests,
            "rejection_reason": rejection_reason,
        }
    )

    return _NormalizedQualityJudgment(
        judgment=normalized,
        repaired=repaired,
    )
